### ISSUE TITLE
ALT/ETC Market TVL Calculation

### ISSUE THREAD

**Issue by chris-mercer** [etcswap/v3-info#12]
### Bug Description
In an ALT/ETC market, the TVL is only calculating the ETC value of the pool.

### Steps to Reproduce
https://info.etcswap.org/#/classic/pools/0xbb4c07ae47994889734ea229a1b484e25cc0dec9
https://etc.blockscout.com/address/0xbb4c07ae47994889734ea229a1b484e25cc0dec9

Math:
ETC = ($23.70 * 29.44) = 701.69 of TVL
NYKE = ($0.0005 * 603,891) = 301.94 of TVL
Total TVL = ~$1,003

### Expected Behavior
TVL = (ETC spot price * ETC amount) + (ALT spot price * ALT amount)

### Additional Context
![image](https://github.com/user-attachments/assets/be53f55b-41bd-4ed0-bd5b-448fd5337067)

**Comment by leon-do** [comment]
fixed
