### ISSUE TITLE
ALT/USC Market TVL Calculation

### ISSUE THREAD

**Issue by chris-mercer** [etcswap/v3-info#13]
### Bug Description
In an ALT/USC market, the TVL is only calculating the USC value of the pool.

### Steps to Reproduce
https://info.etcswap.org/#/classic/pools/0xa64cb403a44a5270ee0b82bca09a302b3bc2bc57
https://etc.blockscout.com/address/0xa64cb403a44a5270ee0b82bca09a302b3bc2bc57

Math:
USC = ($1 * 498.26) = 498.26 of TVL
NYKE = ($0.0005 * 1,035,418) = 517.70 of TVL
Total TVL = ~$1,015

### Expected Behavior
TVL = (USC spot price * USC amount) + (ALT spot price * ALT amount)

### Additional Context
![image](https://github.com/user-attachments/assets/3e901af2-b1ff-4246-8b17-420162cfc7bd)

**Comment by leon-do** [comment]
fixed
