### ISSUE TITLE
Update Links

### ISSUE THREAD

**Issue by chris-mercer** [etcswap/v3-info#15]

**Comment by chris-mercer** [comment]
![Image](https://github.com/user-attachments/assets/f0ab20b8-a11b-4519-b7f8-1a1e798f98d8)

**Comment by leon-do** [comment]
https://github.com/etcswap/v3-info/pull/17

**Comment by leon-do** [comment]
there's not a link to all of the marktes. for example what about https://info.etcswap.org/#/tokens/0x8fcda99ca0dc616009d26b6ba080d27591015f26

**Comment by chris-mercer** [comment]
@leon-do could we add a swap icon to the right for the token assets and pools?

https://github.com/etcswap/v3-info/issues/26

token Page: https://info.etcswap.org/#/tokens/0xde093684c796204224bc081f937aa059d903c52a

Swap link: https://v3.etcswap.org/#/swap?chain=classic&inputCurrency=ETC&outputCurrency=0xDE093684c796204224BC081f937aa059D903c52a&exactAmount=1

**Comment by leon-do** [comment]
will close because this is done https://github.com/etcswap/v3-info/pull/17
