### ISSUE TITLE
Add Swap to Header

### ISSUE THREAD

**Issue by chris-mercer** [etcswap/v3-info#21]

**Comment by chris-mercer** [comment]
![Image](https://github.com/user-attachments/assets/891a0ef9-0633-40e3-a239-df2407978034)

**Comment by leon-do** [comment]
https://github.com/etcswap/v3-info/pull/17

**Comment by chris-mercer** [comment]
![Image](https://github.com/user-attachments/assets/19a3adbd-cda1-4266-bc57-e1d6a5353921)

**Comment by leon-do** [comment]
https://github.com/etcswap/v3-info/pull/33
