### ISSUE TITLE
Pool Page: Backwards Liquidity Chart

### ISSUE THREAD

**Issue by chris-mercer** [etcswap/v3-info#25]

**Comment by chris-mercer** [comment]
![Image](https://github.com/user-attachments/assets/6f77281d-db2c-4fb8-a9af-09c743f6ffd6)

**Comment by leon-do** [comment]
https://github.com/etcswap/v3-info/pull/28

**Comment by chris-mercer** [comment]
Can we match colors from Swap UI @leon-do ?


![Image](https://github.com/user-attachments/assets/afc9fea3-7bb3-4b5a-bef7-2a52d75050ca)

**Comment by leon-do** [comment]
primary1 is the color you set

**Comment by chris-mercer** [comment]
I'll look into what I used for this chart
![Image](https://github.com/user-attachments/assets/454e80af-39c5-4b95-acff-1b930d1430c9)
