### ISSUE TITLE
Hide $0 TVL tokens

### ISSUE THREAD

**Issue by chris-mercer** [etcswap/v3-info#29]

**Comment by chris-mercer** [comment]
![Image](https://github.com/user-attachments/assets/56cfd30b-3066-4a34-968b-643827225ede)

**Comment by chris-mercer** [comment]
Overview and Tokens page



![Image](https://github.com/user-attachments/assets/4f93b717-65fc-4e4b-8108-7ab288a21926)

**Comment by leon-do** [comment]
https://github.com/etcswap/v3-info/pull/34
