### ISSUE TITLE
Hide $0 7D Volume Pools

### ISSUE THREAD

**Issue by chris-mercer** [etcswap/v3-info#31]

**Comment by chris-mercer** [comment]
![Image](https://github.com/user-attachments/assets/6d510a0a-7f56-4081-93e9-a24537776991)

**Comment by chris-mercer** [comment]
Overview and on Pool page:



![Image](https://github.com/user-attachments/assets/3c4a56c1-f917-4f80-991a-8c021657b40e)

**Comment by chris-mercer** [comment]
Top Movers:



![Image](https://github.com/user-attachments/assets/75ac6c28-f993-40f0-890d-018b0092b6c1)

**Comment by leon-do** [comment]
https://github.com/etcswap/v3-info/pull/34

**Comment by leon-do** [comment]
https://github.com/etcswap/v3-info/pull/34/files
